# Generated by Django 4.1.4 on 2023-01-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('smell', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
    ]
